//! `sys::` constants mapped into Rust enums.
//!
//! D-M0-2: the safe wrapper never re-declares a numeric value. Every enum here
//! is generated by [`vt_enum!`] from the `sys::` constants themselves, so a
//! re-vendor that renames a constant is a compile error at the mapping site and
//! one that renumbers it cannot desynchronise the two — there is only one copy
//! of each number, and it lives in the generated bindings.
//!
//! The macro also emits `ALL`, which is what lets
//! `tests/enums.rs::every_wrapper_enum_round_trips_through_its_sys_constant`
//! walk every variant of every enum without a hand-maintained list going stale.
//!
//! [`Key`](crate::key::Key) is declared in [`crate::key`] rather than here: it
//! is 176 variants on its own and the module budget is a forcing function, not
//! a suggestion.

use crate::sys;

/// Declare a Rust enum over a set of `sys::` constants.
///
/// The constants are named, never copied: `to_sys` returns the `sys::` value
/// and `from_sys` matches on it, so the numbers exist exactly once, in the
/// bindings generated from the vendored headers at build time.
macro_rules! vt_enum {
    (
        $(#[$meta:meta])*
        $name:ident: $raw:ty {
            $( $(#[$variant_meta:meta])* $variant:ident = $constant:path ),+ $(,)?
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub enum $name {
            $( $(#[$variant_meta])* $variant, )+
        }

        impl $name {
            /// Every variant, in the order the header declares them.
            pub const ALL: &'static [Self] = &[ $( Self::$variant, )+ ];

            /// The name of this enum, for [`UnknownVariant`](crate::error::UnknownVariant).
            pub const NAME: &'static str = stringify!($name);

            /// The `sys::` constant this variant stands for.
            #[must_use]
            pub fn to_sys(self) -> $raw {
                match self {
                    $( Self::$variant => $constant, )+
                }
            }

            /// Map a `sys::` constant back to a variant.
            ///
            /// `None` means the vendored library produced a value this build
            /// does not know — possible, because `vt.h` says the API is not
            /// stable — and the caller decides whether that is fatal.
            #[must_use]
            pub fn from_sys(raw: $raw) -> Option<Self> {
                match raw {
                    $( $constant => Some(Self::$variant), )+
                    _ => None,
                }
            }
        }
    };
}

pub(crate) use vt_enum;

vt_enum! {
    /// How much of a frame changed, as the render state reports it.
    ///
    /// `include/ghostty/vt/render.h:60` describes the two independent layers:
    /// this global state, and a per-row flag. Clearing one does not clear the
    /// other, which is why [`Snapshot`](crate::Snapshot) publication clears
    /// both explicitly.
    Dirty: sys::GhosttyRenderStateDirty::Type {
        /// Nothing changed; the frame can be skipped entirely.
        Clean = sys::GhosttyRenderStateDirty::GHOSTTY_RENDER_STATE_DIRTY_FALSE,
        /// Some rows changed; the per-row flags say which.
        Partial = sys::GhosttyRenderStateDirty::GHOSTTY_RENDER_STATE_DIRTY_PARTIAL,
        /// Global state changed; every row must be redrawn.
        Full = sys::GhosttyRenderStateDirty::GHOSTTY_RENDER_STATE_DIRTY_FULL,
    }
}

vt_enum! {
    /// The shape the cursor should be drawn with.
    ///
    /// This is the render state's copy (`render.h:118`); the terminal has a
    /// separate `GhosttyTerminalCursorStyle` with the same shapes for the
    /// DECSCUSR *default*, which amx does not set.
    #[derive(Default)]
    CursorStyle: sys::GhosttyRenderStateCursorVisualStyle::Type {
        /// Vertical bar (DECSCUSR 5, 6).
        Bar = sys::GhosttyRenderStateCursorVisualStyle::GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_BAR,
        /// Filled block (DECSCUSR 1, 2) — what DECSCUSR resets to.
        #[default]
        Block = sys::GhosttyRenderStateCursorVisualStyle::GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_BLOCK,
        /// Underline (DECSCUSR 3, 4).
        Underline =
            sys::GhosttyRenderStateCursorVisualStyle::GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_UNDERLINE,
        /// Hollow block, drawn when the terminal is unfocused.
        BlockHollow =
            sys::GhosttyRenderStateCursorVisualStyle::GHOSTTY_RENDER_STATE_CURSOR_VISUAL_STYLE_BLOCK_HOLLOW,
    }
}

vt_enum! {
    /// Which screen buffer the terminal is currently on.
    Screen: sys::GhosttyTerminalScreen::Type {
        /// The primary screen — the one with scrollback.
        Primary = sys::GhosttyTerminalScreen::GHOSTTY_TERMINAL_SCREEN_PRIMARY,
        /// The alternate screen, which has no scrollback and does not reflow.
        Alternate = sys::GhosttyTerminalScreen::GHOSTTY_TERMINAL_SCREEN_ALTERNATE,
    }
}

vt_enum! {
    /// How wide a cell is, and whether it is a spacer for a wide neighbour.
    ///
    /// A renderer must skip the spacers: they carry no text of their own.
    #[derive(Default)]
    CellWide: sys::GhosttyCellWide::Type {
        /// One column.
        #[default]
        Narrow = sys::GhosttyCellWide::GHOSTTY_CELL_WIDE_NARROW,
        /// Two columns; the second is a [`CellWide::SpacerTail`].
        Wide = sys::GhosttyCellWide::GHOSTTY_CELL_WIDE_WIDE,
        /// The second column of a wide character. Do not render.
        SpacerTail = sys::GhosttyCellWide::GHOSTTY_CELL_WIDE_SPACER_TAIL,
        /// Padding at the end of a soft-wrapped line before a wide character.
        SpacerHead = sys::GhosttyCellWide::GHOSTTY_CELL_WIDE_SPACER_HEAD,
    }
}

vt_enum! {
    /// What kind of content a cell holds.
    CellContent: sys::GhosttyCellContentTag::Type {
        /// A single codepoint, possibly zero for an empty cell.
        Codepoint = sys::GhosttyCellContentTag::GHOSTTY_CELL_CONTENT_CODEPOINT,
        /// A codepoint that begins a multi-codepoint grapheme cluster.
        Grapheme = sys::GhosttyCellContentTag::GHOSTTY_CELL_CONTENT_CODEPOINT_GRAPHEME,
        /// No text; a palette background colour.
        BackgroundPalette = sys::GhosttyCellContentTag::GHOSTTY_CELL_CONTENT_BG_COLOR_PALETTE,
        /// No text; an RGB background colour.
        BackgroundRgb = sys::GhosttyCellContentTag::GHOSTTY_CELL_CONTENT_BG_COLOR_RGB,
    }
}

vt_enum! {
    /// Which of a style's three colour slots is populated.
    StyleColor: sys::GhosttyStyleColorTag::Type {
        /// Unset; the renderer supplies its own default.
        None = sys::GhosttyStyleColorTag::GHOSTTY_STYLE_COLOR_NONE,
        /// An index into the 256-colour palette.
        Palette = sys::GhosttyStyleColorTag::GHOSTTY_STYLE_COLOR_PALETTE,
        /// A direct RGB value.
        Rgb = sys::GhosttyStyleColorTag::GHOSTTY_STYLE_COLOR_RGB,
    }
}

vt_enum! {
    /// The underline style an SGR sequence selected.
    #[derive(Default)]
    Underline: sys::GhosttySgrUnderline::Type {
        /// No underline.
        #[default]
        None = sys::GhosttySgrUnderline::GHOSTTY_SGR_UNDERLINE_NONE,
        /// A single line.
        Single = sys::GhosttySgrUnderline::GHOSTTY_SGR_UNDERLINE_SINGLE,
        /// Two lines.
        Double = sys::GhosttySgrUnderline::GHOSTTY_SGR_UNDERLINE_DOUBLE,
        /// A wavy line, conventionally a spell-check marker.
        Curly = sys::GhosttySgrUnderline::GHOSTTY_SGR_UNDERLINE_CURLY,
        /// A dotted line.
        Dotted = sys::GhosttySgrUnderline::GHOSTTY_SGR_UNDERLINE_DOTTED,
        /// A dashed line.
        Dashed = sys::GhosttySgrUnderline::GHOSTTY_SGR_UNDERLINE_DASHED,
    }
}

vt_enum! {
    /// The coordinate space a [`Point`](crate::history::Point) is expressed in.
    ///
    /// `include/ghostty/vt/point.h:45`. Active and viewport lookups are cheap;
    /// screen and history lookups may walk the whole page list, which is why
    /// [`crate::history`] documents its reads as bulk operations.
    PointSpace: sys::GhosttyPointTag::Type {
        /// The area the cursor can move in.
        Active = sys::GhosttyPointTag::GHOSTTY_POINT_TAG_ACTIVE,
        /// What is currently visible, which moves when the user scrolls.
        Viewport = sys::GhosttyPointTag::GHOSTTY_POINT_TAG_VIEWPORT,
        /// Scrollback and active area together.
        Screen = sys::GhosttyPointTag::GHOSTTY_POINT_TAG_SCREEN,
        /// Scrollback only, before the active area.
        History = sys::GhosttyPointTag::GHOSTTY_POINT_TAG_HISTORY,
    }
}

vt_enum! {
    /// Which clipboard an OSC 52 write is aimed at.
    ClipboardLocation: sys::GhosttyClipboardLocation::Type {
        /// The system clipboard.
        Standard = sys::GhosttyClipboardLocation::GHOSTTY_CLIPBOARD_LOCATION_STANDARD,
        /// The selection clipboard.
        Selection = sys::GhosttyClipboardLocation::GHOSTTY_CLIPBOARD_LOCATION_SELECTION,
        /// The primary selection.
        Primary = sys::GhosttyClipboardLocation::GHOSTTY_CLIPBOARD_LOCATION_PRIMARY,
    }
}

vt_enum! {
    /// What the embedder did with a clipboard write.
    ///
    /// OSC 52 has no acknowledgement, so libghostty-vt ignores everything but
    /// the fact that the callback returned; amx reports
    /// [`ClipboardWriteResult::Success`] and forwards the write to the client.
    ClipboardWriteResult: sys::GhosttyClipboardWriteResult::Type {
        /// The write was accepted.
        Success = sys::GhosttyClipboardWriteResult::GHOSTTY_CLIPBOARD_WRITE_RESULT_SUCCESS,
        /// Policy or the user refused it.
        Denied = sys::GhosttyClipboardWriteResult::GHOSTTY_CLIPBOARD_WRITE_RESULT_DENIED,
        /// The destination or a representation is not supported.
        Unsupported = sys::GhosttyClipboardWriteResult::GHOSTTY_CLIPBOARD_WRITE_RESULT_UNSUPPORTED,
        /// The clipboard is temporarily unavailable.
        Busy = sys::GhosttyClipboardWriteResult::GHOSTTY_CLIPBOARD_WRITE_RESULT_BUSY,
        /// A representation held invalid data.
        InvalidData = sys::GhosttyClipboardWriteResult::GHOSTTY_CLIPBOARD_WRITE_RESULT_INVALID_DATA,
        /// The write failed with an I/O error.
        IoError = sys::GhosttyClipboardWriteResult::GHOSTTY_CLIPBOARD_WRITE_RESULT_IO_ERROR,
    }
}

vt_enum! {
    /// The colour scheme reported in answer to `CSI ? 996 n`.
    ColorScheme: sys::GhosttyColorScheme::Type {
        /// A light background.
        Light = sys::GhosttyColorScheme::GHOSTTY_COLOR_SCHEME_LIGHT,
        /// A dark background.
        Dark = sys::GhosttyColorScheme::GHOSTTY_COLOR_SCHEME_DARK,
    }
}

vt_enum! {
    /// Whether a row is part of a shell prompt, per OSC 133.
    ///
    /// The agent layer (05 M2) reads this; M0 only carries it through the
    /// snapshot so the row type does not have to change later.
    RowSemanticPrompt: sys::GhosttyRowSemanticPrompt::Type {
        /// No prompt cells on this row.
        None = sys::GhosttyRowSemanticPrompt::GHOSTTY_ROW_SEMANTIC_NONE,
        /// A primary prompt line.
        Prompt = sys::GhosttyRowSemanticPrompt::GHOSTTY_ROW_SEMANTIC_PROMPT,
        /// A prompt continuation line.
        PromptContinuation = sys::GhosttyRowSemanticPrompt::GHOSTTY_ROW_SEMANTIC_PROMPT_CONTINUATION,
    }
}
