//! Raw FFI declarations for libghostty-vt.
//!
//! Generated by `bindgen` at build time from the vendored headers under
//! `vendor/libghostty-vt/include` and included from `OUT_DIR`; nothing in this
//! file is committed beyond the include itself. 04 §3 asks for exactly that:
//! the bindings cannot drift from the headers because they do not outlive a
//! build.
//!
//! Everything here is `unsafe` to call and unstable by construction — `vt.h`
//! opens by warning that the API "is not yet stable and is definitely going to
//! change". The safe surface is the rest of this crate; nothing outside
//! `amx-vt` should name a `sys::` item.
#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    missing_docs,
    missing_debug_implementations,
    clippy::all,
    clippy::pedantic,
    unsafe_op_in_unsafe_fn,
    reason = "generated by bindgen"
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
