//! The physical key table.
//!
//! One variant per `GHOSTTY_KEY_*` constant in
//! `include/ghostty/vt/key/event.h`, in the header's own order and under its
//! own section headings, so the two can be diffed by eye after a re-vendor.

use crate::enums::vt_enum;
use crate::sys;

vt_enum! {
    /// A physical key, layout-independent.
    ///
    /// These are the W3C UI Events `code` values: the `a` key on a US keyboard
    /// and the `ф` key on a Russian one are both [`Key::A`]. Layout-dependent
    /// text is carried separately, by
    /// [`KeyEvent::set_text`](crate::KeyEvent::set_text).
    ///
    /// Every variant is named exactly after the `GHOSTTY_KEY_*` constant it
    /// maps to, so a per-variant doc comment would only repeat the name.
    #[allow(missing_docs, reason = "each variant is its W3C UI Events code")]
    Key: sys::GhosttyKey::Type {
        Unidentified = sys::GhosttyKey::GHOSTTY_KEY_UNIDENTIFIED,

        // Writing System Keys (W3C § 3.1.1)
        Backquote = sys::GhosttyKey::GHOSTTY_KEY_BACKQUOTE,
        Backslash = sys::GhosttyKey::GHOSTTY_KEY_BACKSLASH,
        BracketLeft = sys::GhosttyKey::GHOSTTY_KEY_BRACKET_LEFT,
        BracketRight = sys::GhosttyKey::GHOSTTY_KEY_BRACKET_RIGHT,
        Comma = sys::GhosttyKey::GHOSTTY_KEY_COMMA,
        Digit0 = sys::GhosttyKey::GHOSTTY_KEY_DIGIT_0,
        Digit1 = sys::GhosttyKey::GHOSTTY_KEY_DIGIT_1,
        Digit2 = sys::GhosttyKey::GHOSTTY_KEY_DIGIT_2,
        Digit3 = sys::GhosttyKey::GHOSTTY_KEY_DIGIT_3,
        Digit4 = sys::GhosttyKey::GHOSTTY_KEY_DIGIT_4,
        Digit5 = sys::GhosttyKey::GHOSTTY_KEY_DIGIT_5,
        Digit6 = sys::GhosttyKey::GHOSTTY_KEY_DIGIT_6,
        Digit7 = sys::GhosttyKey::GHOSTTY_KEY_DIGIT_7,
        Digit8 = sys::GhosttyKey::GHOSTTY_KEY_DIGIT_8,
        Digit9 = sys::GhosttyKey::GHOSTTY_KEY_DIGIT_9,
        Equal = sys::GhosttyKey::GHOSTTY_KEY_EQUAL,
        IntlBackslash = sys::GhosttyKey::GHOSTTY_KEY_INTL_BACKSLASH,
        IntlRo = sys::GhosttyKey::GHOSTTY_KEY_INTL_RO,
        IntlYen = sys::GhosttyKey::GHOSTTY_KEY_INTL_YEN,
        A = sys::GhosttyKey::GHOSTTY_KEY_A,
        B = sys::GhosttyKey::GHOSTTY_KEY_B,
        C = sys::GhosttyKey::GHOSTTY_KEY_C,
        D = sys::GhosttyKey::GHOSTTY_KEY_D,
        E = sys::GhosttyKey::GHOSTTY_KEY_E,
        F = sys::GhosttyKey::GHOSTTY_KEY_F,
        G = sys::GhosttyKey::GHOSTTY_KEY_G,
        H = sys::GhosttyKey::GHOSTTY_KEY_H,
        I = sys::GhosttyKey::GHOSTTY_KEY_I,
        J = sys::GhosttyKey::GHOSTTY_KEY_J,
        K = sys::GhosttyKey::GHOSTTY_KEY_K,
        L = sys::GhosttyKey::GHOSTTY_KEY_L,
        M = sys::GhosttyKey::GHOSTTY_KEY_M,
        N = sys::GhosttyKey::GHOSTTY_KEY_N,
        O = sys::GhosttyKey::GHOSTTY_KEY_O,
        P = sys::GhosttyKey::GHOSTTY_KEY_P,
        Q = sys::GhosttyKey::GHOSTTY_KEY_Q,
        R = sys::GhosttyKey::GHOSTTY_KEY_R,
        S = sys::GhosttyKey::GHOSTTY_KEY_S,
        T = sys::GhosttyKey::GHOSTTY_KEY_T,
        U = sys::GhosttyKey::GHOSTTY_KEY_U,
        V = sys::GhosttyKey::GHOSTTY_KEY_V,
        W = sys::GhosttyKey::GHOSTTY_KEY_W,
        X = sys::GhosttyKey::GHOSTTY_KEY_X,
        Y = sys::GhosttyKey::GHOSTTY_KEY_Y,
        Z = sys::GhosttyKey::GHOSTTY_KEY_Z,
        Minus = sys::GhosttyKey::GHOSTTY_KEY_MINUS,
        Period = sys::GhosttyKey::GHOSTTY_KEY_PERIOD,
        Quote = sys::GhosttyKey::GHOSTTY_KEY_QUOTE,
        Semicolon = sys::GhosttyKey::GHOSTTY_KEY_SEMICOLON,
        Slash = sys::GhosttyKey::GHOSTTY_KEY_SLASH,

        // Functional Keys (W3C § 3.1.2)
        AltLeft = sys::GhosttyKey::GHOSTTY_KEY_ALT_LEFT,
        AltRight = sys::GhosttyKey::GHOSTTY_KEY_ALT_RIGHT,
        Backspace = sys::GhosttyKey::GHOSTTY_KEY_BACKSPACE,
        CapsLock = sys::GhosttyKey::GHOSTTY_KEY_CAPS_LOCK,
        ContextMenu = sys::GhosttyKey::GHOSTTY_KEY_CONTEXT_MENU,
        ControlLeft = sys::GhosttyKey::GHOSTTY_KEY_CONTROL_LEFT,
        ControlRight = sys::GhosttyKey::GHOSTTY_KEY_CONTROL_RIGHT,
        Enter = sys::GhosttyKey::GHOSTTY_KEY_ENTER,
        MetaLeft = sys::GhosttyKey::GHOSTTY_KEY_META_LEFT,
        MetaRight = sys::GhosttyKey::GHOSTTY_KEY_META_RIGHT,
        ShiftLeft = sys::GhosttyKey::GHOSTTY_KEY_SHIFT_LEFT,
        ShiftRight = sys::GhosttyKey::GHOSTTY_KEY_SHIFT_RIGHT,
        Space = sys::GhosttyKey::GHOSTTY_KEY_SPACE,
        Tab = sys::GhosttyKey::GHOSTTY_KEY_TAB,
        Convert = sys::GhosttyKey::GHOSTTY_KEY_CONVERT,
        KanaMode = sys::GhosttyKey::GHOSTTY_KEY_KANA_MODE,
        NonConvert = sys::GhosttyKey::GHOSTTY_KEY_NON_CONVERT,

        // Control Pad Section (W3C § 3.2)
        Delete = sys::GhosttyKey::GHOSTTY_KEY_DELETE,
        End = sys::GhosttyKey::GHOSTTY_KEY_END,
        Help = sys::GhosttyKey::GHOSTTY_KEY_HELP,
        Home = sys::GhosttyKey::GHOSTTY_KEY_HOME,
        Insert = sys::GhosttyKey::GHOSTTY_KEY_INSERT,
        PageDown = sys::GhosttyKey::GHOSTTY_KEY_PAGE_DOWN,
        PageUp = sys::GhosttyKey::GHOSTTY_KEY_PAGE_UP,

        // Arrow Pad Section (W3C § 3.3)
        ArrowDown = sys::GhosttyKey::GHOSTTY_KEY_ARROW_DOWN,
        ArrowLeft = sys::GhosttyKey::GHOSTTY_KEY_ARROW_LEFT,
        ArrowRight = sys::GhosttyKey::GHOSTTY_KEY_ARROW_RIGHT,
        ArrowUp = sys::GhosttyKey::GHOSTTY_KEY_ARROW_UP,

        // Numpad Section (W3C § 3.4)
        NumLock = sys::GhosttyKey::GHOSTTY_KEY_NUM_LOCK,
        Numpad0 = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_0,
        Numpad1 = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_1,
        Numpad2 = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_2,
        Numpad3 = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_3,
        Numpad4 = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_4,
        Numpad5 = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_5,
        Numpad6 = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_6,
        Numpad7 = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_7,
        Numpad8 = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_8,
        Numpad9 = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_9,
        NumpadAdd = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_ADD,
        NumpadBackspace = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_BACKSPACE,
        NumpadClear = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_CLEAR,
        NumpadClearEntry = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_CLEAR_ENTRY,
        NumpadComma = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_COMMA,
        NumpadDecimal = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_DECIMAL,
        NumpadDivide = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_DIVIDE,
        NumpadEnter = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_ENTER,
        NumpadEqual = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_EQUAL,
        NumpadMemoryAdd = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_MEMORY_ADD,
        NumpadMemoryClear = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_MEMORY_CLEAR,
        NumpadMemoryRecall = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_MEMORY_RECALL,
        NumpadMemoryStore = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_MEMORY_STORE,
        NumpadMemorySubtract = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_MEMORY_SUBTRACT,
        NumpadMultiply = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_MULTIPLY,
        NumpadParenLeft = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_PAREN_LEFT,
        NumpadParenRight = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_PAREN_RIGHT,
        NumpadSubtract = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_SUBTRACT,
        NumpadSeparator = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_SEPARATOR,
        NumpadUp = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_UP,
        NumpadDown = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_DOWN,
        NumpadRight = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_RIGHT,
        NumpadLeft = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_LEFT,
        NumpadBegin = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_BEGIN,
        NumpadHome = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_HOME,
        NumpadEnd = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_END,
        NumpadInsert = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_INSERT,
        NumpadDelete = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_DELETE,
        NumpadPageUp = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_PAGE_UP,
        NumpadPageDown = sys::GhosttyKey::GHOSTTY_KEY_NUMPAD_PAGE_DOWN,

        // Function Section (W3C § 3.5)
        Escape = sys::GhosttyKey::GHOSTTY_KEY_ESCAPE,
        F1 = sys::GhosttyKey::GHOSTTY_KEY_F1,
        F2 = sys::GhosttyKey::GHOSTTY_KEY_F2,
        F3 = sys::GhosttyKey::GHOSTTY_KEY_F3,
        F4 = sys::GhosttyKey::GHOSTTY_KEY_F4,
        F5 = sys::GhosttyKey::GHOSTTY_KEY_F5,
        F6 = sys::GhosttyKey::GHOSTTY_KEY_F6,
        F7 = sys::GhosttyKey::GHOSTTY_KEY_F7,
        F8 = sys::GhosttyKey::GHOSTTY_KEY_F8,
        F9 = sys::GhosttyKey::GHOSTTY_KEY_F9,
        F10 = sys::GhosttyKey::GHOSTTY_KEY_F10,
        F11 = sys::GhosttyKey::GHOSTTY_KEY_F11,
        F12 = sys::GhosttyKey::GHOSTTY_KEY_F12,
        F13 = sys::GhosttyKey::GHOSTTY_KEY_F13,
        F14 = sys::GhosttyKey::GHOSTTY_KEY_F14,
        F15 = sys::GhosttyKey::GHOSTTY_KEY_F15,
        F16 = sys::GhosttyKey::GHOSTTY_KEY_F16,
        F17 = sys::GhosttyKey::GHOSTTY_KEY_F17,
        F18 = sys::GhosttyKey::GHOSTTY_KEY_F18,
        F19 = sys::GhosttyKey::GHOSTTY_KEY_F19,
        F20 = sys::GhosttyKey::GHOSTTY_KEY_F20,
        F21 = sys::GhosttyKey::GHOSTTY_KEY_F21,
        F22 = sys::GhosttyKey::GHOSTTY_KEY_F22,
        F23 = sys::GhosttyKey::GHOSTTY_KEY_F23,
        F24 = sys::GhosttyKey::GHOSTTY_KEY_F24,
        F25 = sys::GhosttyKey::GHOSTTY_KEY_F25,
        Fn = sys::GhosttyKey::GHOSTTY_KEY_FN,
        FnLock = sys::GhosttyKey::GHOSTTY_KEY_FN_LOCK,
        PrintScreen = sys::GhosttyKey::GHOSTTY_KEY_PRINT_SCREEN,
        ScrollLock = sys::GhosttyKey::GHOSTTY_KEY_SCROLL_LOCK,
        Pause = sys::GhosttyKey::GHOSTTY_KEY_PAUSE,

        // Media Keys (W3C § 3.6)
        BrowserBack = sys::GhosttyKey::GHOSTTY_KEY_BROWSER_BACK,
        BrowserFavorites = sys::GhosttyKey::GHOSTTY_KEY_BROWSER_FAVORITES,
        BrowserForward = sys::GhosttyKey::GHOSTTY_KEY_BROWSER_FORWARD,
        BrowserHome = sys::GhosttyKey::GHOSTTY_KEY_BROWSER_HOME,
        BrowserRefresh = sys::GhosttyKey::GHOSTTY_KEY_BROWSER_REFRESH,
        BrowserSearch = sys::GhosttyKey::GHOSTTY_KEY_BROWSER_SEARCH,
        BrowserStop = sys::GhosttyKey::GHOSTTY_KEY_BROWSER_STOP,
        Eject = sys::GhosttyKey::GHOSTTY_KEY_EJECT,
        LaunchApp1 = sys::GhosttyKey::GHOSTTY_KEY_LAUNCH_APP_1,
        LaunchApp2 = sys::GhosttyKey::GHOSTTY_KEY_LAUNCH_APP_2,
        LaunchMail = sys::GhosttyKey::GHOSTTY_KEY_LAUNCH_MAIL,
        MediaPlayPause = sys::GhosttyKey::GHOSTTY_KEY_MEDIA_PLAY_PAUSE,
        MediaSelect = sys::GhosttyKey::GHOSTTY_KEY_MEDIA_SELECT,
        MediaStop = sys::GhosttyKey::GHOSTTY_KEY_MEDIA_STOP,
        MediaTrackNext = sys::GhosttyKey::GHOSTTY_KEY_MEDIA_TRACK_NEXT,
        MediaTrackPrevious = sys::GhosttyKey::GHOSTTY_KEY_MEDIA_TRACK_PREVIOUS,
        Power = sys::GhosttyKey::GHOSTTY_KEY_POWER,
        Sleep = sys::GhosttyKey::GHOSTTY_KEY_SLEEP,
        AudioVolumeDown = sys::GhosttyKey::GHOSTTY_KEY_AUDIO_VOLUME_DOWN,
        AudioVolumeMute = sys::GhosttyKey::GHOSTTY_KEY_AUDIO_VOLUME_MUTE,
        AudioVolumeUp = sys::GhosttyKey::GHOSTTY_KEY_AUDIO_VOLUME_UP,
        WakeUp = sys::GhosttyKey::GHOSTTY_KEY_WAKE_UP,

        // Legacy, Non-standard, and Special Keys (W3C § 3.7)
        Copy = sys::GhosttyKey::GHOSTTY_KEY_COPY,
        Cut = sys::GhosttyKey::GHOSTTY_KEY_CUT,
        Paste = sys::GhosttyKey::GHOSTTY_KEY_PASTE,
    }
}
